/** 목업 인덱스 — 8공간 + 조사 리포트 + 참조 화면. */

import {LayoutContent} from '@astryxdesign/core/Layout';
import {shell, SPACES} from '../../../ui/shell.mjs';
import {h, Card, Text, Badge, sectionLabel, id, grid} from '../../../ui/components.mjs';

export const title = 'Orc Citadel — 목업 인덱스';

/** 공간 → (설명, 담당 설계 문서). */
const DETAIL = {
  'citadel-gate': ['조사 요청 진입점 · Campaign 목록 · 시스템 상태 요약', 'POST /v1/investigations'],
  'war-table': ['엔티티·주장·증거의 Temporal Evidence Graph', '02 · 06'],
  'hall-of-witnesses': ['claim ↔ 원문 span 왕복 · 지지/반박 · 독립성', '03 §8 · 05'],
  'council-chamber': ['Agent 계획·토론·반증·종합 · 조사 루프·비용', '07 · 09'],
  'watchtower': ['source 상태·backlog·freshness·failure 감시', '04 · 11'],
  'grand-archive': ['원문·버전·parsing·출처 계보(dedup lineage)', '03 · 04 · 08'],
  'chronicle-vault': ['valid time × transaction time · bitemporal', '03 §6 · 09'],
  'signal-spire': ['결론·confidence 변화 · 신규 모순 알림', '11 §4 · 09'],
};

const body = h(LayoutContent, {padding: 4},
  h('div', {style: {display: 'flex', alignItems: 'center', gap: 14, marginBottom: 16}},
    h('img', {src: './assets/logo-mark.png', alt: 'Orc Citadel 문장',
      style: {height: 56, width: 'auto', flex: 'none'}}),
    h(Text, {type: 'supporting'},
    'Astryx + theme-citadel 로 재작성한 8공간과 조사 리포트 정적 목업. '
      + '컴포넌트는 빌드 시점에 정적 HTML 로 렌더되며 클라이언트 JS 는 없다.')),
  h('div', {style: {marginTop: 20}},
    grid(4, 16, ...SPACES.map(([slug, name, role]) => {
      const [desc, spec] = DETAIL[slug];
      // 준비된 공간 히어로 삽화 8종을 카드 썸네일로 — 파일명은 `<slug>-hero.png`,
      // citadel-gate 만 역사적 이유로 `gate-hero.png`.
      const hero = slug === 'citadel-gate' ? 'gate-hero.png' : `${slug}-hero.png`;
      return h('a', {key: slug, href: `./${slug}.html`, style: {textDecoration: 'none'}},
        h(Card, {}, h('div', {style: {padding: 4}},
          h('div', {style: {aspectRatio: '8 / 3', borderRadius: 'var(--radius-inner)',
            overflow: 'hidden', marginBottom: 10,
            background: `url('./assets/${hero}') center / cover no-repeat, var(--color-background-surface)`}}),
          h('div', {style: {fontFamily: 'var(--font-family-heading)', fontSize: 14,
            fontWeight: 600, color: 'var(--color-text-primary)'}}, name),
          h('div', {style: {marginTop: 2}}, h(Text, {type: 'supporting'}, role)),
          h('div', {style: {marginTop: 8, minHeight: 34}},
            h(Text, {type: 'supporting'}, desc)),
          h('div', {style: {marginTop: 8, display: 'flex', alignItems: 'center',
            justifyContent: 'space-between'}},
            id(spec),
            h('span', {style: {fontSize: 11,
              color: 'var(--astryx-theme-citadel-seer-green)'}}, '열기 ›')))));
    }))),
  sectionLabel('조사 리포트 · Investigation Reports'),
  grid(2, 16,
    h('a', {href: './campaign-ledger.html', style: {textDecoration: 'none'}},
      h(Card, {}, h('div', {style: {padding: 4}},
        h('div', {style: {aspectRatio: '8 / 3', borderRadius: 'var(--radius-inner)',
          overflow: 'hidden', marginBottom: 10,
          background: "url('./assets/campaign-ledger-hero.png') center / cover no-repeat, var(--color-background-surface)"}}),
        h('div', {style: {fontFamily: 'var(--font-family-heading)', fontSize: 14,
          fontWeight: 600, color: 'var(--color-text-primary)'}},
          'Campaign Ledger · 조사 보고서'),
        h('div', {style: {marginTop: 4, minHeight: 34}},
          h(Text, {type: 'supporting'},
            '전체 조사 상태를 탐색하고 감사 가능한 HTML 리포트를 여는 Council utility')),
        h('div', {style: {marginTop: 8, display: 'flex', alignItems: 'center',
          justifyContent: 'space-between'}},
          h(Badge, {variant: 'success', label: 'MASTER · DETAIL'}),
          h('span', {style: {fontSize: 11,
            color: 'var(--astryx-theme-citadel-seer-green)'}}, '열기 ›'))))),
    h('a', {href: './investigation-report.html', style: {textDecoration: 'none'}},
      h(Card, {}, h('div', {style: {padding: 4}},
        h('div', {style: {aspectRatio: '8 / 3', borderRadius: 'var(--radius-inner)',
          overflow: 'hidden', marginBottom: 10, padding: 14,
          display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
          border: '1px solid var(--color-border)',
          background: 'linear-gradient(135deg, var(--color-background-muted), var(--color-background-surface))'}},
          h('div', {style: {fontFamily: 'var(--font-family-heading)', fontSize: 9,
            letterSpacing: '.12em', color: 'var(--color-text-secondary)'}},
            'CAMPAIGN LEDGER · INVESTIGATION REPORT'),
          h('div', {style: {display: 'grid', gridTemplateColumns: 'repeat(3,1fr)',
            gap: 4}},
            ['CONCLUSION', 'EVIDENCE', 'AUDIT'].map((label) =>
              h('span', {key: label, style: {padding: '5px 6px',
                border: '1px solid var(--color-border)',
                fontFamily: 'var(--font-family-code)', fontSize: 8,
                color: 'var(--color-text-secondary)'}}, label)))),
        h('div', {style: {fontFamily: 'var(--font-family-heading)', fontSize: 14,
          fontWeight: 600, color: 'var(--color-text-primary)'}},
          'Investigation Report · HTML Artifact'),
        h('div', {style: {marginTop: 4, minHeight: 34}},
          h(Text, {type: 'supporting'},
            '결론·근거·timeline·Audit·재현 메타데이터를 담은 독립 리포트 문서')),
        h('div', {style: {marginTop: 8, display: 'flex', alignItems: 'center',
          justifyContent: 'space-between'}},
          h(Badge, {variant: 'neutral', label: 'PRINT · NO JS'}),
          h('span', {style: {fontSize: 11,
            color: 'var(--astryx-theme-citadel-seer-green)'}}, '열기 ›')))))),
  sectionLabel('참조'),
  grid(2, 16,
    h('a', {href: './project-introduction.html', style: {textDecoration: 'none'}},
      h(Card, {}, h('div', {style: {padding: 4}},
        h('div', {style: {aspectRatio: '8 / 3', borderRadius: 'var(--radius-inner)',
          overflow: 'hidden', marginBottom: 10,
          background: "url('./assets/project-introduction-hero.png') center / cover no-repeat, var(--color-background-surface)"}}),
        h('div', {style: {fontFamily: 'var(--font-family-heading)', fontSize: 14,
          fontWeight: 600, color: 'var(--color-text-primary)'}}, '프로젝트 소개 · Investigation Flow'),
        h('div', {style: {marginTop: 4}},
          h(Text, {type: 'supporting'}, '질문에서 근거 추적 가능한 결론까지의 흐름')),
        h('div', {style: {marginTop: 8, display: 'flex', justifyContent: 'space-between'}},
          h(Badge, {variant: 'success', label: '현재 + 다음'}),
          h('span', {style: {fontSize: 11,
            color: 'var(--astryx-theme-citadel-seer-green)'}}, '열기 ›'))))),
    h('a', {href: './empty-states.html', style: {textDecoration: 'none'}},
      h(Card, {}, h('div', {style: {padding: 4, display: 'flex', alignItems: 'center',
        justifyContent: 'space-between', gap: 12}},
        h('div', {},
          h('div', {style: {fontFamily: 'var(--font-family-heading)', fontSize: 14,
            fontWeight: 600, color: 'var(--color-text-primary)'}}, '빈 상태 아트 · Empty States'),
          h('div', {style: {marginTop: 4}},
            h(Text, {type: 'supporting'}, '각 공간의 no-data 상태 일러스트 6종'))),
        h(Badge, {variant: 'neutral', label: '참조'}))))));

export const render = () => shell({
  route: null,
  eyebrow: 'Mockups · Index',
  context: '목업 인덱스',
  title: 'Orc Citadel · 목업 인덱스',
  subtitle: 'Citadel 8공간 · Campaign Ledger · HTML Report · Astryx',
  alerts: 3,
  slots: {content: body},
});
