"""theme-citadel 계약 회귀 — `DESIGN.md`(SSOT) ↔ 생성된 `dist/theme.css`.

`design-system/theme-citadel/dist/theme.css` 는 `astryx theme build` 생성물이며
리포에 커밋된다(런타임·배포에 node 를 요구하지 않기 위해). 생성물이 SSOT 값과
어긋난 채로 커밋되는 것을 막는 가드다. node 없이 CSS 텍스트만 읽어 검사한다.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

THEME_CSS = (
    Path(__file__).resolve().parents[2]
    / "design-system"
    / "theme-citadel"
    / "dist"
    / "theme.css"
)

# DESIGN.md front-matter 정본 → Astryx 코어 토큰 이름.
# 값을 바꾸려면 DESIGN.md 를 먼저 고치고 citadelTheme.ts 를 재빌드한다.
CORE_TOKENS = {
    # Surfaces — Basalt & Night
    "--color-background-body": "#07111C",  # citadel-void
    "--color-background-surface": "#0D1B2A",  # citadel-night
    "--color-background-card": "#111820",  # surface
    "--color-background-muted": "#26313A",  # surface-variant
    # 경계 — Black iron (그림자 대신 경계선)
    "--color-border": "#26313A",
    # Foreground — Stone
    "--color-text-primary": "#D6CCB8",  # on-surface
    "--color-text-secondary": "#59636A",  # on-surface-muted
    # Graph & Evidence — Emerald
    "--color-accent": "#45E06F",  # primary · war-green
    "--color-on-accent": "#07111C",  # button-primary textColor
    # Status
    "--color-error": "#E05252",
    "--color-warning": "#FFB13B",  # signal-amber
    # Shapes — DESIGN.md rounded sm/md/lg
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
}

# Astryx 코어 토큰 표면에 대응물이 없는 Citadel 고유 값.
LOCAL_TOKENS = {
    "--astryx-theme-citadel-parchment": "#C8B58E",
    "--astryx-theme-citadel-seer-green": "#20B85A",  # secondary
    "--astryx-theme-citadel-ember": "#E97824",
    "--astryx-theme-citadel-signal-amber": "#FFB13B",
    "--astryx-theme-citadel-crimson": "#7B2833",
    "--astryx-theme-citadel-uncertain": "#A78BFA",
    "--astryx-theme-citadel-superseded": "#59636A",
    "--astryx-theme-citadel-font-display": "Cinzel, Georgia, serif",
}


@pytest.fixture(scope="module")
def css() -> str:
    if not THEME_CSS.exists():  # pragma: no cover - 빌드 누락 시에만
        pytest.fail(
            f"{THEME_CSS} 없음 — design-system/theme-citadel 에서 `npm run build` 후 커밋한다."
        )
    return THEME_CSS.read_text(encoding="utf-8")


def _values(css: str, token: str) -> list[str]:
    return [v.strip() for v in re.findall(rf"{re.escape(token)}:\s*([^;]+);", css)]


@pytest.mark.parametrize("token,expected", sorted(CORE_TOKENS.items()))
def test_core_token_matches_design_md(css: str, token: str, expected: str) -> None:
    assert expected in _values(css, token), (
        f"{token} 가 DESIGN.md 값 {expected} 과 다르다 — 재빌드 누락 또는 SSOT 표류"
    )


@pytest.mark.parametrize("token,expected", sorted(LOCAL_TOKENS.items()))
def test_local_token_matches_design_md(css: str, token: str, expected: str) -> None:
    assert expected in _values(css, token)


def test_scoped_to_citadel_theme(css: str) -> None:
    """토큰은 `data-astryx-theme="citadel"` 로 스코프된다 — 전역 오염 금지."""
    assert '@scope ([data-astryx-theme="citadel"])' in css


def test_dark_only_surfaces_have_no_light_dark(css: str) -> None:
    """다크 전용 테마 — 표면·전경 토큰에 light-dark() 가 끼면 안 된다."""
    for token in (
        "--color-background-body",
        "--color-background-surface",
        "--color-background-card",
        "--color-text-primary",
        "--color-accent",
    ):
        assert not any("light-dark(" in v for v in _values(css, token)), token


def test_is_single_scheme_dark_only(css: str) -> None:
    """DESIGN.md 에 라이트 모드가 없다 — 테마도 단일 스킴이어야 한다.

    `defineTheme` 의 `color:` 스케일 설정을 쓰면 HCT 가 light/dark 두 벌을 만들고
    `:root { color-scheme: light dark }` 를 발행한다. 그러면 여기서 덮지 않은
    토큰이 OS 라이트 모드에서 전부 밝은 값으로 뒤집힌다. 다크 전용 선례
    (theme-gothic)도 `color:` 없이 단일 값 토큰만 쓴다.
    """
    assert "color-scheme: light dark" not in css


def test_generated_header_records_provenance(css: str) -> None:
    """생성물임과 소스·CLI 버전이 헤더에 남아야 손으로 고치는 사고를 막는다."""
    assert "@generated by `astryx theme build`" in css
    assert "src/citadelTheme.ts" in css
