/**
 * 폰트 vendoring — DESIGN.md 의 4역할 폰트를 로컬 woff2 + @font-face 로 굽는다.
 *
 * 왜 vendoring 인가: 뷰어·목업 모두 **외부 CDN 금지**가 규약이다(오프라인 전제).
 * Astryx 테마는 `font-family` 이름만 선언하고 "폰트 로딩은 소비자 책임"이라 명시한다.
 * 그 소비자 몫을 여기서 한 번 처리하고 생성물(`dist/`)을 커밋한다 — 런타임에 node 불필요.
 *
 * 네 서체 모두 SIL OFL-1.1 이라 재배포가 허용된다. 라이선스 원문을 dist 에 동봉한다.
 *
 * 한계(정직): Cinzel·Space Grotesk·Inter·JetBrains Mono 는 **한글 글리프가 없다.**
 * UI 본문 상당수가 한글이라 Hangul 은 시스템 폰트로 폴백한다. 원본 목업도 동일했다.
 * 한글 서체 도입은 DESIGN.md 에 정의가 없어 범위 밖 — 필요하면 별도 결정 사항.
 *
 *   node build.mjs
 */

import {mkdirSync, copyFileSync, writeFileSync, rmSync, statSync, readFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, 'dist');
const NM = join(ROOT, 'node_modules', '@fontsource');

/**
 * 실제로 쓰는 (서체 × 굵기)만 가져온다 — 전 굵기를 받으면 6MB 가 넘는다.
 * 굵기는 DESIGN.md typography 절에서 왔다.
 *   display  Cinzel 700          — 워드마크
 *   heading  Space Grotesk 500·600 — 제목·라벨·배지
 *   body     Inter 400·600        — 본문·테이블·강조
 *   code     JetBrains Mono 400   — ID·hash·timestamp·source span
 *
 * subset 은 latin + latin-ext 만 (키릴·그리스는 이 도메인에서 안 쓴다).
 */
const FAMILIES = [
  {pkg: 'cinzel', family: 'Cinzel', weights: [700], role: 'display'},
  {pkg: 'space-grotesk', family: 'Space Grotesk', weights: [500, 600], role: 'heading'},
  {pkg: 'inter', family: 'Inter', weights: [400, 600], role: 'body'},
  {pkg: 'jetbrains-mono', family: 'JetBrains Mono', weights: [400], role: 'code'},
];

const SUBSETS = ['latin', 'latin-ext'];

/**
 * fontsource 의 굵기별 CSS 에서 해당 서브셋 파일의 `unicode-range` 를 뽑아온다.
 * 값을 손으로 적으면 틀리기 쉽고, 틀리면 글리프 누락으로만 드러나 디버깅이 어렵다.
 */
function unicodeRangeFor(pkg, weight, file) {
  const css = readFileSync(join(NM, pkg, `${weight}.css`), 'utf8');
  for (const block of css.split('@font-face')) {
    if (!block.includes(file)) continue;
    const m = block.match(/unicode-range:\s*([^;]+);/);
    if (m) return m[1].trim();
  }
  throw new Error(`unicode-range 없음: ${pkg} ${weight} ${file}`);
}

rmSync(DIST, {recursive: true, force: true});
mkdirSync(join(DIST, 'files'), {recursive: true});

const faces = [];
let bytes = 0;

for (const {pkg, family, weights, role} of FAMILIES) {
  for (const weight of weights) {
    for (const subset of SUBSETS) {
      const file = `${pkg}-${subset}-${weight}-normal.woff2`;
      const src = join(NM, pkg, 'files', file);
      let size;
      try {
        size = statSync(src).size;
      } catch {
        console.warn(`  ! 건너뜀 (없음): ${file}`);
        continue;
      }
      copyFileSync(src, join(DIST, 'files', file));
      bytes += size;
      faces.push({family, weight, subset, file, role, size,
        unicodeRange: unicodeRangeFor(pkg, weight, file)});
    }
  }
  // OFL 재배포 조건 — 라이선스 원문 동봉.
  try {
    copyFileSync(join(NM, pkg, 'LICENSE'), join(DIST, `LICENSE-${pkg}.txt`));
  } catch {
    console.warn(`  ! LICENSE 없음: ${pkg}`);
  }
}

/**
 * `unicode-range` 는 fontsource 가 제공하는 값을 **파싱해서** 가져온다.
 *
 * 이게 없으면 같은 family+weight 선언이 둘(latin·latin-ext)이라 뒤엣것이 이기고
 * 기본 라틴 글리프가 통째로 사라진다. 범위를 손으로 적으면 틀리기 쉬워 원본을 읽는다.
 */
const css = `/*
 * @generated by design-system/fonts/build.mjs — do not edit manually.
 * DESIGN.md typography 4역할 · SIL OFL-1.1 (LICENSE-*.txt 동봉)
 * 한글 글리프 없음 — Hangul 은 시스템 폰트 폴백 (build.mjs 주석 참조)
 */
${faces.map(f => `@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url("./files/${f.file}") format("woff2");
  unicode-range: ${f.unicodeRange};
}`).join('\n')}
`;

writeFileSync(join(DIST, 'fonts.css'), css);

for (const {role, family, weight, subset, size} of faces) {
  console.log(`  ${role.padEnd(8)} ${family} ${weight} ${subset.padEnd(10)} ${(size / 1024).toFixed(1)}KB`);
}
console.log(`\n${faces.length} faces · ${(bytes / 1024).toFixed(1)}KB total`);
